spring.application.name=api-sistema-biblioteca

spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotecadb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Propiedades extra muy útiles para desarrollo:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
